[package]
name = "os"
version = "0.1.0"
edition = "2021"

[dependencies]
framebuffer = "0.3.1"
embedded-graphics = "0.7.1"
embedded_graphics_framebuffer = "0.1.1"
ctrlc = "3.4.2"
chrono = "0.4.33"
console = "0.15.8"
crossterm = "0.28.1"

[build-dependencies]
chrono = "0.4.33"